config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index', as: 'home'


  get 'about' => 'pages#about', as: 'about'



  resources :posts do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  has_many :comments
  validates :title, presence: true, length: {minimum: 5}
  belongs_to :user, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def self.from_omniauth(auth)
    where (auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
    end 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def show
    @post = Post.find(params[:post_id])
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end 

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  #implementing Twitter Sign-In API using OmniAuth 

  def twitter
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      sign_in_and_redirect user, notice: "Signed in via Twitter!"
    else
      redirect_to new_user_registration_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    @title = 'About Me'
    @content = 'This is the about page'
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    # index will be a list of posts
    @posts = current_user.posts.all.order("id DESC")
  end

  def show
    @post = current_user.posts.find(params[:id])
  end

  def new
    # form to add post
    @post = current_user.posts.build
  end

  def create
    # check if submitted to create: render plain: params[:post].inspect
    @post = current_user.posts.build(post_params)
    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if (@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/show.html.erb
<h3> Comments </h3>
<% @post.comments.each do |comment| %>
  <div class="well">
    <p><strong><%= comment.username %></strong>: <%= comment.body %><p>
  </div>
<% end %>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <% controller.redirect_to posts_path %>
<% else %>
  <h1> Welcome to the home page </h1>
  <p> Please sign up or log in. </p>
  <%= link_to "Register", new_user_registration_path, :class => 'btn btn-default' %>
  <%= link_to "Log In", new_user_session_path, :class => 'btn btn-default' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>

    <!-- Adding Bootstrap CSS -->
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- navbar from startbootstrap -->
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Simple Blog</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", home_path %></li>
            <li><%= link_to "About", about_path %> </li>

            <!-- Dropdown menu template
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            -->
          </ul>

          <ul class="nav navbar-nav navbar-right">

            <% if user_signed_in? %>
              <li><%= link_to "Log Out", destroy_user_session_path, :method => 'delete' %></li>
            <% else %>
              <li><%= link_to "Register", new_user_registration_path %></li>
              <li><%= link_to "Log In", new_user_session_path %></li>
            <% end %>

            <li><a href="posts/new">New Post</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <% if !user_signed_in? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>


    <div class="container">
      <%= yield %>
    </div>



  </body>
</html>

app/views/pages/about.html.erb
<h1> <%= @title %> </h1>
<p> <%= @content %> </p>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

  <!-- Validate form -->
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Here are all the blog posts: </h1>

<% @posts.each do |post| %>
  <div class="well">
    <h2> <%= post.title %> </h2>
    <p> <%= post.body %> </p>
    <%= link_to "Read more", post_path(post), :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1> Add New Post </h1>
<!-- submits to create method -->
<%= form_for :post, url: posts_path do |f| %>

  <!-- Validate form -->
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p> <%= @post.body %> <p>

<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post),
                method: :delete,
                data: {confirm: 'Are you sure you want to delete this post?'},
                :class => 'btn btn-danger' %>

<%= link_to "Back", home_path, :class => 'btn btn-primary' %>

<hr>

<hr>

<h3> Add a Comment </h3>
<%= form_for ([@post, @post.comments.build]) do |f| %>

  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <p>
    <%= f.label :username %> <br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-default'}) %>
  </p>
<% end %>